apiVersion: 1

datasources:
  - name: Infinity
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: infinity_fastapi
    jsonData:
      tlsSkipVerify: true
    editable: false
    isDefault: false

